ports:
- port: 8000
  onOpen: open-preview
tasks:
- init: yarn install
  command: >
    yarn grunt fastBuild &&
    printf "\nWelcome to Learn Git Branching\nTo rebuild the app, simply run 'yarn grunt fastBuild' and reload index.html.\n\n" &&
    python3 -m http.server 8000 2>/dev/null
