all: prep.html overview.html commands.html

prep.html: prep.md
	python3 build.py prep.md

overview.html: overview.md
	python3 build.py overview.md

commands.html: commands.md
	python3 build.py commands.md
